### ISSUE TITLE
Poshify extension changes Shopify global styling when enabled

### ISSUE THREAD

**Issue by bootsified** [husseyexplores/poshify-utilities#14]
Around the first of the year (2022), I think, I started noticing that the layout was jacked in the Shopify admin, but only in Firefox.  I assumed it was an issue with a Shopify update that would be fixed soon, but it went on for months.  I finally spent some time recently and discovered that it was being caused by the Poshify extension.  I only have it installed in Firefox, so I assume that's why everything looked fine in Chrome.  I can't figure out exactly what the issue is, but there is something in the Poshify extension that is overriding the global CSS font size in the Shopify admin or something.  When I disable the extension, it all looks fine.

Here is a screenshot of the uneffected page:
![poshify-bug-disabled](https://user-images.githubusercontent.com/1693606/173696829-3099fa18-d68c-4133-9cbf-358ec31f0f22.png)

...and here is a screenshot of the page with the Poshify extension enabled:
![poshify-bug-enabled](https://user-images.githubusercontent.com/1693606/173696930-3b5d1c40-09ec-4362-ba0f-2abd24f9d9e2.png)

I totally understand this is a free extension, so I mainly just wanted to give you the heads-up.  Poshify has been a life-saver for me, so I want to THANK YOU for all the time you've put into it to this point.  For now, I just keep the extension disabled until I need it, which works fine for me.  I look forward to not having to do that in the future, tho.  🙌

**Comment by nemecky** [comment]
Looks like this has happened again. Seems Shopify updated their global styling for the admin area, and when this extension is enabled it throws off the layout, changes colors, etc.

**Comment by rsimmons-eca** [comment]
Can confirm this is also happening to me too. If you have access to the shopify partners slack channel, some people realized this here: https://shopifypartners.slack.com/archives/C4E704GBX/p1704207417675979

**Comment by husseyexplores** [comment]
Acknowledged. 
Will try to release an update as soon as I get some spare time.

**Comment by husseyexplores** [comment]
Fixed it.
Please update your extension!
