### ISSUE TITLE
New metafield types not supported

### ISSUE THREAD

**Issue by nemecky** [husseyexplores/poshify-utilities#15]
I just realized this today when I discovered numerous blog posts we had initially hidden from the store search and search engines using the "seo hidden" metafield were now appearing in the SERPs as well as store search results. This particular metafield used the Integer type, which is no longer supported, and is now Number_Integer. Luckily this client has ACF installed so I was able to go in and edit the metafields quickly that way. 

Here's the new list of metafield types 
https://shopify.dev/apps/metafields/types

**Comment by husseyexplores** [comment]
Released v4 which supports new types!
