### ISSUE TITLE
ERROR: Shopify Admin is not detected 

### ISSUE THREAD

**Issue by Candice-Leif** [husseyexplores/poshify-utilities#17]
We have recently noticed that when trying to use the Poshify App for our product Metafeilds, it doesn't seem to be connecting to our store front. We are seeing the error "Shopify Admin is not detected" when attempting to connect to the extension.

No code changed have been made in the last few months and I was able to amend a new product week commencing December 12th. Has there been any changes made with in the extension?

**Comment by husseyexplores** [comment]
Hi Candice,

Glad to hear that you found Poshify useful.

I'm working on a new version of Poshify as we speak - which will be
released in a week. It'll have more options and will support the latest
Shopify metafield types.
Until then, you may have to use any app from the app store.
Metafields Guru may fit your needs in the meantime and has a free tier.

**Comment by husseyexplores** [comment]
Not to mention, the new release of the extension will also support some dynamic/bulk metafeild creation as well. 
But it will take a couple of months for these fancy features. The core extension will be released in a week.

**Comment by husseyexplores** [comment]
Glad to hear that you found Poshify useful.

I'm working on a new version of Poshify as we speak - which will be released in a week. It'll have more options and will support the latest Shopify metafield types.

Until then, you may have to use any app from the app store.

Metafields Guru may fit your needs in the meantime and has a free tier.

--- 
Not to mention, the new release of the extension will also support some dynamic/bulk metafeild creation as well.
But it will take a couple of months for these fancy features. The core extension will be released in a week.

**Comment by husseyexplores** [comment]
@Candice-Leif New version v4 has been released :tada: . If you notice any issues, have feedback, or require any features feel free to open another issue!
