### ISSUE TITLE
Unable to fetch shop info query

### ISSUE THREAD

**Issue by nsdool** [husseyexplores/poshify-utilities#19]
Just started receiving this error today when trying to open Poshify: 

_Unable to fetch shop info query. Retry reloading or open a ticket on github. ([PoshifyUtils] - Unable to complete authentication. (No csrf tokens found))_

We love this extension, btw! Just wanted to give you a heads up that this error was happening. Thanks!

**Comment by husseyexplores** [comment]
Thanks for the heads up. I can also see that happening on my end.
Give me a couple of days to investigate this and I'll publish the fix as soon as I can.

> We love this extension, btw! 

I'm glad! :)

**Comment by nsdool** [comment]
Thank you!

**Comment by bansavage** [comment]
Seeing the same error, thanks for looking into it @husseyexplores

**Comment by husseyexplores** [comment]
Published the fix! 
I'll take a day or two for Chrome web store to approve the new version.

**Comment by husseyexplores** [comment]
The fix has been published and approved. Just update your extension.

**Comment by nsdool** [comment]
Awesome! Thank you!
