### ISSUE TITLE
Can't edit any products on shopify admin

### ISSUE THREAD

**Issue by livingeartbeauty** [husseyexplores/poshify-utilities#20]
our admin is not allowing us to edit any meta fields and products at this point. what are we supposed to do?

**Comment by husseyexplores** [comment]
The issue has been patched. It will take a couple of days for the Chrome extension to be published.

**Comment by husseyexplores** [comment]
Patch has been published. Update your browser extension!

**Comment by livingeartbeauty** [comment]
Ok thank you. Is poshify going to continue on being supported or is this being deprecated due to shopify updates?

**Comment by husseyexplores** [comment]
I plan to support this at least for another year.
By support, I mean only bug fixes and/or any critical updates.
