### ISSUE TITLE
Poshify not able to edit products

### ISSUE THREAD

**Issue by rpank5** [husseyexplores/poshify-utilities#21]
Hi there, I've been having issues with poshify not working correctly when I try to edit products on my shopify store. It looks like this on all stores when I select the product category. Please are you able to advise 
<img width="1053" alt="Screenshot 2024-07-05 at 09 50 29" src="https://github.com/husseyexplores/poshify-utilities/assets/174786257/6af7cb0e-efea-4533-9114-908178306476">

**Comment by husseyexplores** [comment]
Thanks for the heads up.
A new version has been published. It's pending approval from the Chrome webstore. 
Will be released a day or two. Be sure to update your extension to version 4.7.1 if it's not updated automatically.
