### ISSUE TITLE
Issue on searching for products

### ISSUE THREAD

**Issue by livingeartbeauty** [husseyexplores/poshify-utilities#23]
When searching for products in the poshify tab the page returns erroneous results. see screenshot.
<img width="1068" alt="Screenshot 2024-07-05 at 12 46 07 PM" src="https://github.com/husseyexplores/poshify-utilities/assets/164689171/b553d8a2-94b7-4f49-bfb6-6d6803b45b88">

**Comment by husseyexplores** [comment]
Already fixed and released the updated version. Please update your extension.

**Comment by livingeartbeauty** [comment]
Is there a way to export all of the unstructured metafield data out of the
poshify app since the app is being sunsetted?
Living Earth Beauty

*www.LivingEarthBeauty.com <http://www.livingearthbeauty.com/>*

*Follow us on Instagram <https://instagram.com/livingearthbeauty/>*
*Become a fan on Facebook <http://facebook.com/livingearthbeauty>*
*Tweet with us on Twitter <http://twitter.com/livingearthlive>*
*Read our Blog <http://blog.livingearthbeauty.com/>*

*Love sharing our products? Learn how to become an affiliate
<https://www.livingearthbeauty.com/affiliates>.*
