### ISSUE TITLE
any doc how to use

### ISSUE THREAD

**Issue by wanghaisheng** [husseyexplores/poshify-utilities#4]
when i create new field for one product .it just not display when i preview

**Comment by husseyexplores** [comment]
Sorry, I couldn't understand what you meant by

> it just not display when i preview

Can you please elaborate more?

**Comment by wanghaisheng** [comment]
i finally figure out  i have to manually edit theme code , product.liquid to control  new metafield 
it is not what i thought at first  which  i only need to do metafield definition

**Comment by husseyexplores** [comment]
Yep. The extension only creates the metafield for the selected resource.

And in order to use that metafield, you have to edit theme files or use it on server-side, or whatever your use case is.
