### ISSUE TITLE
Plugin Down

### ISSUE THREAD

**Issue by hov310** [husseyexplores/poshify-utilities#6]
![Screen Shot 2020-08-24 at 10 45 18 AM](https://user-images.githubusercontent.com/52506459/91078061-ec749400-e5f6-11ea-8f7a-09e3cfa23340.png)

Not able to edit Metafields as of today

**Comment by husseyexplores** [comment]
Thanks for the heads up. I'll publish the fix in a day or two.

You should be still able to edit the metafields by:
1. Searching the product from the extension.
2. Or navigating to that product in Shopify admin, and then clicking on the `Current Resource` button from the extension.

**Comment by husseyexplores** [comment]
Fixed in v3.0.0
