### ISSUE TITLE
Cannot load Shop metafields

### ISSUE THREAD

**Issue by vasiliki-b-zz** [husseyexplores/poshify-utilities#8]
**Description**
- Selecting the `Shop` option from the dropdown in the editor results in an infinite loading screen.

**Environment**
  - macOS Big Sur Version 11.2.2
  - Chrome Version 89.0.4389.82 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/16694090/110404403-c7a0b500-804c-11eb-8c97-e266fcad470f.png)

**Comment by husseyexplores** [comment]
I've tried this on multiple shops and it's working correctly.

I suggest that you should first try logging out and logging in again, it may help.

If not, please tell me:
1. Do other resources are working correctly?
2. Before selecting the `shop` option, open up the browser dev tools and watch the network tab. Then select the `shop` option and see if the ajax request is successful or not? If not, what error/status code is it?

**Comment by vasiliki-b-zz** [comment]
Looking at the Network tab as you suggested, after I click on Shop it just continuously repeats the calls, as shown in the image below:

<img width="309" alt="Screen Shot 2021-03-15 at 7 47 12 PM" src="https://user-images.githubusercontent.com/16694090/111235566-4e164300-85c7-11eb-8246-d6d5f097148e.png">

The responses are 200 but for some reason it keeps repeating? I have tried unmounting/mounting the app and also removing completely and re-adding.

**Comment by husseyexplores** [comment]
Okay. Can you tell me how many metafields are there on the `shop` resource? 
You can get the total count from here: 
`https://change-this-handle-to-your-shop.myshopify.com/admin/api/2020-10/metafields/count.json`

Don't forget to change the myshopify subdomain to the correct shop.

I think the shop has too many metafields. We currently fetch all the metafields, assuming there will be 5 or fewer pages.

**Comment by vasiliki-b-zz** [comment]
37150 😵

**Comment by husseyexplores** [comment]
Thanks for reporting this. That's an edge case for sure. I'll add a "load more" button if there are > 2000 metafields. Hopefully within the next month!

**Comment by vasiliki-b** [comment]
By the way, the other ones work (product, pages, collections, etc.)
It's only the `Shop` that doesn't work.
